/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 plane.gltf
Author: Alberto Soliveres (https://sketchfab.com/soliveres)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ft-spitfire-rc-airplane-assembly-7ebf054f2e8e40deaf45e35132680bf6
Title: FT SPITFIRE - RC - Airplane Assembly
*/

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/plane.gltf')
  const ref = useRef()

  useFrame(({ mouse, viewport }) => {
    const x = (mouse.x * viewport.width) / 100
    const y = (mouse.y * viewport.height) / 100
    ref.current.lookAt(x * 0.1, y * 0.1, 1)
  })

  return (
    <group {...props} scale={1.8} dispose={null} ref={ref}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.material_3} position={[-47.05, -240.29, -20.03]} rotation={[-3.05, 0, 3.11]} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.material_3} position={[110.9, -365.96, 13.27]} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.material_3} position={[-251.59, 0.3, 441.11]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.material_3} position={[-38.38, -378.05, -44.97]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.material_3} position={[-18.98, 411.29, -43.06]} rotation={[-Math.PI, Math.PI / 2, 0]} />
        <group position={[-5.81, -55.22, -442.9]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Object_28.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.material_3} />
        </group>
        <mesh geometry={nodes.Object_33.geometry} material={materials.material_3} position={[110.9, -365.96, 13.27]} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.material_3} position={[-251.59, 0.3, 441.11]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.material_3} position={[108.5, -0.3, 441.15]} rotation={[-Math.PI / 2, 0, 0]} />
        <group position={[-297.48, -123.74, 0]}>
          <mesh geometry={nodes.Object_43.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Object_45.geometry} material={materials.material_3} />
        </group>
        <group position={[-297.48, -123.74, 0]}>
          <mesh geometry={nodes.Object_49.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Object_51.geometry} material={materials.material_3} />
        </group>
        <mesh geometry={nodes.Object_54.geometry} material={materials.material_3} position={[-297.48, -123.74, 0]} />
        <group position={[5.99, -55.22, -442.9]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Object_62.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Object_64.geometry} material={materials.material_3} />
        </group>
        <group position={[17.79, -55.22, -442.9]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Object_68.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Object_70.geometry} material={materials.material_3} />
        </group>
        <mesh geometry={nodes.Object_73.geometry} material={materials.material_3} position={[-131.9, -37.95, -1.73]} rotation={[-3.05, 0, 3.11]} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.material_3} position={[8.28, -63.1, 274.79]} rotation={[-1.48, -1.57, 0]} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.material_3} position={[8.3, -15.05, -274.42]} rotation={[1.66, 1.57, 0]} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.material_3} position={[99.77, -236.73, -5.52]} rotation={[0.09, -0.12, 0.03]} />
        <group position={[8.24, 50.89, 6.63]} rotation={[0.09, 0, 0.03]}>
          <mesh geometry={nodes.Object_86.geometry} material={materials.material_7} />
          <mesh geometry={nodes.Object_87.geometry} material={materials.material_7} />
          <mesh geometry={nodes.Object_89.geometry} material={materials.material_8} />
          <mesh geometry={nodes.Object_91.geometry} material={materials.material_9} />
        </group>
        <group position={[-58.62, 0.43, 7.8]} rotation={[0, 0, 0.06]}>
          <mesh geometry={nodes.Object_95.geometry} material={materials.material_7} />
          <mesh geometry={nodes.Object_96.geometry} material={materials.material_7} />
          <mesh geometry={nodes.Object_98.geometry} material={materials.material_8} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.material_9} />
        </group>
        <group position={[-58.62, -0.43, 7.8]} rotation={[-Math.PI, 0, 0.06]}>
          <mesh geometry={nodes.Object_104.geometry} material={materials.material_7} />
          <mesh geometry={nodes.Object_105.geometry} material={materials.material_7} />
          <mesh geometry={nodes.Object_107.geometry} material={materials.material_8} />
          <mesh geometry={nodes.Object_109.geometry} material={materials.material_9} />
        </group>
        <mesh geometry={nodes.Object_112.geometry} material={materials.material_10} position={[-58.2, -3.27, 7.8]} rotation={[-0.84, -1.49, 2.3]} />
        <mesh geometry={nodes.Object_115.geometry} material={materials.material_10} position={[-58.2, 3.27, 7.8]} rotation={[0, 0, 0.06]} />
        <mesh geometry={nodes.Object_118.geometry} material={materials.material_10} position={[8.75, 53.75, 6.88]} rotation={[-2.8, 1.44, 2.89]} />
        <mesh geometry={nodes.Object_129.geometry} material={materials.material_11} position={[33.22, -3.8, 7.89]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_132.geometry} material={materials.material_12} position={[-5.37, 52.67, 7.41]} rotation={[-3.05, 0.12, 3.11]} />
        <mesh geometry={nodes.Object_135.geometry} material={materials.material_12} position={[8.28, 54.07, 5.33]} rotation={[-1.48, -0.03, 2.1]} />
        <mesh geometry={nodes.Object_138.geometry} material={materials.material_12} position={[-75.88, 0.3, 17.46]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_141.geometry} material={materials.material_12} position={[-73.21, 0, 13.27]} rotation={[Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_144.geometry} material={materials.material_12} position={[-71.86, 28.34, 13.27]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <group position={[12.88, 0, 7.48]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
          <mesh geometry={nodes.Object_148.geometry} material={materials.material_13} />
          <mesh geometry={nodes.Object_150.geometry} material={materials.material_14} />
          <mesh geometry={nodes.Object_152.geometry} material={materials.material_14} />
          <mesh geometry={nodes.Object_154.geometry} material={materials.material_14} />
          <mesh geometry={nodes.Object_156.geometry} material={materials.material_15} />
          <mesh geometry={nodes.Object_158.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_160.geometry} material={materials.material_17} />
          <mesh geometry={nodes.Object_162.geometry} material={materials.material_4} />
          <mesh geometry={nodes.Object_164.geometry} material={materials.material_18} />
          <mesh geometry={nodes.Object_166.geometry} material={materials.material_19} />
          <mesh geometry={nodes.Object_168.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_170.geometry} material={materials.material_17} />
          <mesh geometry={nodes.Object_172.geometry} material={materials.material_4} />
        </group>
        <mesh geometry={nodes.Object_175.geometry} material={materials.material_5} position={[-73.55, 0.3, 9.07]} rotation={[Math.PI, 0, Math.PI]} />
        <group position={[19.89, -0.45, 13.88]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Object_183.geometry} material={materials.material_21} />
          <mesh geometry={nodes.Object_185.geometry} material={materials.material_22} />
          <mesh geometry={nodes.Object_187.geometry} material={materials.material_23} />
          <mesh geometry={nodes.Object_189.geometry} material={materials.material_21} />
          <mesh geometry={nodes.Object_191.geometry} material={materials.material_4} />
          <mesh geometry={nodes.Object_193.geometry} material={materials.material_24} />
          <mesh geometry={nodes.Object_195.geometry} material={materials.material_24} />
        </group>
        <group position={[23.35, 0, 7.46]}>
          <mesh geometry={nodes.Object_253.geometry} material={materials.material_9} />
          <mesh geometry={nodes.Object_255.geometry} material={materials.material_28} />
          <mesh geometry={nodes.Object_257.geometry} material={materials.material_9} />
          <mesh geometry={nodes.Object_258.geometry} material={materials.material_9} />
          <mesh geometry={nodes.Object_260.geometry} material={materials.material_29} />
          <mesh geometry={nodes.Object_262.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_264.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_266.geometry} material={materials.material_4} />
        </group>
        <mesh geometry={nodes.Object_269.geometry} material={materials.material_31} position={[15.48, 4.59, 10.28]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_471.geometry} material={materials.material_48} position={[19.89, -3.28, 13.88]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <group position={[28.73, -2.85, 12.45]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Object_475.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_476.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_477.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_478.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_480.geometry} material={materials.material_29} />
          <mesh geometry={nodes.Object_481.geometry} material={materials.material_29} />
          <mesh geometry={nodes.Object_482.geometry} material={materials.material_29} />
          <mesh geometry={nodes.Object_483.geometry} material={materials.material_29} />
          <mesh geometry={nodes.Object_485.geometry} material={materials.material_29} />
          <mesh geometry={nodes.Object_487.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_489.geometry} material={materials.material_4} />
        </group>
        <group position={[-45, 4.45, 8.19]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
          <mesh geometry={nodes.Object_493.geometry} material={materials.material_29} />
          <mesh geometry={nodes.Object_495.geometry} material={materials.material_29} />
          <mesh geometry={nodes.Object_497.geometry} material={materials.material_17} />
          <mesh geometry={nodes.Object_499.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_501.geometry} material={materials.material_4} />
        </group>
        <group position={[20.47, -0.93, 7.91]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Object_505.geometry} material={materials.material_5} />
          <mesh geometry={nodes.Object_507.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_509.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_511.geometry} material={materials.material_17} />
          <mesh geometry={nodes.Object_513.geometry} material={materials.material_4} />
        </group>
        <mesh geometry={nodes.Object_516.geometry} material={materials.material_11} position={[-45.11, 4.45, 8.19]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_519.geometry} material={materials.material_6} position={[-18.16, -3.85, 7.93]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_522.geometry} material={materials.material_5} position={[33.82, 0.03, 10.4]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_525.geometry} material={materials.material_3} position={[-131.9, 37.95, -1.73]} rotation={[-0.09, 0, 3.11]} />
        <mesh geometry={nodes.Object_528.geometry} material={materials.material_3} position={[8.28, 63.1, 274.79]} rotation={[-1.66, 1.57, 0]} />
        <mesh geometry={nodes.Object_531.geometry} material={materials.material_3} position={[8.3, 15.05, -274.42]} rotation={[1.48, -1.57, 0]} />
        <mesh geometry={nodes.Object_534.geometry} material={materials.material_3} position={[-47.05, 240.29, -20.03]} rotation={[-0.09, 0, 3.11]} />
        <mesh geometry={nodes.Object_537.geometry} material={materials.material_3} position={[99.77, 236.73, -5.52]} rotation={[3.05, 0.12, 0.03]} />
        <group position={[8.24, -50.89, 6.63]} rotation={[3.05, 0, 0.03]}>
          <mesh geometry={nodes.Object_541.geometry} material={materials.material_8} />
          <mesh geometry={nodes.Object_543.geometry} material={materials.material_7} />
          <mesh geometry={nodes.Object_544.geometry} material={materials.material_7} />
          <mesh geometry={nodes.Object_546.geometry} material={materials.material_9} />
        </group>
        <mesh geometry={nodes.Object_549.geometry} material={materials.material_49} position={[8.76, -53.45, 6.85]} rotation={[-1.8, -1.54, 1.43]} />
        <mesh geometry={nodes.Object_552.geometry} material={materials.material_12} position={[-5.23, -52.67, 7.43]} rotation={[-0.09, -0.12, 3.11]} />
        <mesh geometry={nodes.Object_555.geometry} material={materials.material_12} position={[8.42, -53.78, 5.3]} rotation={[-1.66, 0.03, 2.1]} />
        <group position={[19.08, 1.08, 16.02]} rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Object_559.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_561.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_563.geometry} material={materials.material_4} />
          <mesh geometry={nodes.Object_565.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_566.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_567.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_569.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_570.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_571.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_573.geometry} material={materials.material_4} />
          <mesh geometry={nodes.Object_574.geometry} material={materials.material_4} />
        </group>
        <group position={[19.82, 1.08, 16.02]} rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Object_578.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_579.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_580.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_581.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_583.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_584.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_585.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_587.geometry} material={materials.material_4} />
          <mesh geometry={nodes.Object_588.geometry} material={materials.material_4} />
          <mesh geometry={nodes.Object_589.geometry} material={materials.material_4} />
          <mesh geometry={nodes.Object_591.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_592.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_593.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_595.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_596.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_598.geometry} material={materials.material_4} />
          <mesh geometry={nodes.Object_599.geometry} material={materials.material_4} />
        </group>
        <group position={[20.28, 0, 0.6]}>
          <mesh geometry={nodes.Object_603.geometry} material={materials.material_5} />
          <mesh geometry={nodes.Object_605.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_607.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_609.geometry} material={materials.material_4} />
          <mesh geometry={nodes.Object_611.geometry} material={materials.material_5} />
          <mesh geometry={nodes.Object_613.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_615.geometry} material={materials.material_30} />
          <mesh geometry={nodes.Object_617.geometry} material={materials.material_4} />
        </group>
        <mesh geometry={nodes.Object_18.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_126.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_179.geometry} material={materials.material_20} />
        <group position={[29.43, -3.22, 18.93]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Object_200.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_202.geometry} material={materials.material_16} />
          <mesh geometry={nodes.Object_204.geometry} material={materials.material_5} />
        </group>
        <group position={[28.73, -2.85, 11.64]} rotation={[0, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Object_208.geometry} material={materials.material_27} />
          <mesh geometry={nodes.Object_210.geometry} material={materials.material_27} />
        </group>
        <group position={[28.73, -2.85, 10.83]} rotation={[0, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Object_214.geometry} material={materials.material_27} />
          <mesh geometry={nodes.Object_216.geometry} material={materials.material_27} />
        </group>
        <group position={[29.73, -2.92, 11.64]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Object_220.geometry} material={materials.material_12} />
          <mesh geometry={nodes.Object_222.geometry} material={materials.material_12} />
        </group>
        <group position={[29.73, -2.92, 10.83]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Object_226.geometry} material={materials.material_12} />
          <mesh geometry={nodes.Object_228.geometry} material={materials.material_12} />
        </group>
        <group position={[29.13, -2.92, 10.83]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Object_232.geometry} material={materials.material_12} />
          <mesh geometry={nodes.Object_234.geometry} material={materials.material_12} />
        </group>
        <group position={[29.13, -2.92, 11.64]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Object_238.geometry} material={materials.material_12} />
          <mesh geometry={nodes.Object_240.geometry} material={materials.material_12} />
        </group>
        <mesh geometry={nodes.Object_243.geometry} material={materials.material_27} position={[28.73, -2.85, 12.45]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_246.geometry} material={materials.material_12} position={[29.73, -2.92, 12.45]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Object_249.geometry} material={materials.material_12} position={[29.13, -2.92, 12.45]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_274.geometry} material={materials.material_32} />
          <mesh geometry={nodes.Object_276.geometry} material={materials.material_33} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_279.geometry} material={materials.material_34} />
          <mesh geometry={nodes.Object_280.geometry} material={materials.material_34} />
          <mesh geometry={nodes.Object_281.geometry} material={materials.material_34} />
          <mesh geometry={nodes.Object_282.geometry} material={materials.material_34} />
          <mesh geometry={nodes.Object_283.geometry} material={materials.material_34} />
          <mesh geometry={nodes.Object_284.geometry} material={materials.material_34} />
          <mesh geometry={nodes.Object_285.geometry} material={materials.material_34} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_288.geometry} material={materials.material_35} />
          <mesh geometry={nodes.Object_289.geometry} material={materials.material_35} />
        </group>
        <mesh geometry={nodes.Object_292.geometry} material={materials.material_37} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_296.geometry} material={materials.material_38} />
          <mesh geometry={nodes.Object_297.geometry} material={materials.material_38} />
          <mesh geometry={nodes.Object_299.geometry} material={materials.material_39} />
          <mesh geometry={nodes.Object_300.geometry} material={materials.material_39} />
          <mesh geometry={nodes.Object_301.geometry} material={materials.material_39} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_305.geometry} material={materials.material_38} />
          <mesh geometry={nodes.Object_306.geometry} material={materials.material_38} />
          <mesh geometry={nodes.Object_308.geometry} material={materials.material_39} />
          <mesh geometry={nodes.Object_309.geometry} material={materials.material_39} />
          <mesh geometry={nodes.Object_310.geometry} material={materials.material_39} />
        </group>
        <group position={[34.17, 0.03, 10.37]} rotation={[1.33, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_313.geometry} material={materials.material_37} />
          <mesh geometry={nodes.Object_314.geometry} material={materials.material_37} />
          <mesh geometry={nodes.Object_315.geometry} material={materials.material_37} />
          <mesh geometry={nodes.Object_316.geometry} material={materials.material_37} />
          <mesh geometry={nodes.Object_317.geometry} material={materials.material_37} />
          <mesh geometry={nodes.Object_318.geometry} material={materials.material_37} />
          <mesh geometry={nodes.Object_319.geometry} material={materials.material_37} />
          <mesh geometry={nodes.Object_320.geometry} material={materials.material_37} />
        </group>
        <group position={[34.17, 0.03, 10.37]} rotation={[2.18, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_323.geometry} material={materials.material_41} />
          <mesh geometry={nodes.Object_324.geometry} material={materials.material_41} />
          <mesh geometry={nodes.Object_325.geometry} material={materials.material_41} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_328.geometry} material={materials.material_37} />
          <mesh geometry={nodes.Object_329.geometry} material={materials.material_37} />
          <mesh geometry={nodes.Object_330.geometry} material={materials.material_37} />
          <mesh geometry={nodes.Object_331.geometry} material={materials.material_37} />
          <mesh geometry={nodes.Object_332.geometry} material={materials.material_37} />
          <mesh geometry={nodes.Object_333.geometry} material={materials.material_37} />
          <mesh geometry={nodes.Object_334.geometry} material={materials.material_37} />
        </group>
        <group position={[34.17, 0.03, 10.37]} rotation={[0.63, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_337.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_338.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_339.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_340.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_341.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_342.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_343.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_344.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_345.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_346.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_347.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_348.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_349.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_350.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_351.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_352.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_353.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_354.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_355.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_356.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_357.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_358.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_359.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_360.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_361.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_362.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_363.geometry} material={materials.material_43} />
          <mesh geometry={nodes.Object_364.geometry} material={materials.material_43} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_367.geometry} material={materials.material_35} />
          <mesh geometry={nodes.Object_368.geometry} material={materials.material_35} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_371.geometry} material={materials.material_35} />
          <mesh geometry={nodes.Object_372.geometry} material={materials.material_35} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_375.geometry} material={materials.material_35} />
          <mesh geometry={nodes.Object_376.geometry} material={materials.material_35} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_379.geometry} material={materials.material_35} />
          <mesh geometry={nodes.Object_380.geometry} material={materials.material_35} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_383.geometry} material={materials.material_35} />
          <mesh geometry={nodes.Object_384.geometry} material={materials.material_35} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_387.geometry} material={materials.material_35} />
          <mesh geometry={nodes.Object_388.geometry} material={materials.material_35} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_391.geometry} material={materials.material_35} />
          <mesh geometry={nodes.Object_392.geometry} material={materials.material_35} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_395.geometry} material={materials.material_35} />
          <mesh geometry={nodes.Object_396.geometry} material={materials.material_35} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_399.geometry} material={materials.material_35} />
          <mesh geometry={nodes.Object_400.geometry} material={materials.material_35} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_403.geometry} material={materials.material_35} />
          <mesh geometry={nodes.Object_404.geometry} material={materials.material_35} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_407.geometry} material={materials.material_35} />
          <mesh geometry={nodes.Object_408.geometry} material={materials.material_35} />
        </group>
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_411.geometry} material={materials.material_44} />
          <mesh geometry={nodes.Object_412.geometry} material={materials.material_44} />
        </group>
        <group position={[34.07, 0.03, 10.37]} rotation={[1.2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_416.geometry} material={materials.material_32} />
          <mesh geometry={nodes.Object_418.geometry} material={materials.material_33} />
          <mesh geometry={nodes.Object_420.geometry} material={materials.material_45} />
        </group>
        <mesh geometry={nodes.Object_423.geometry} material={materials.material_35} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_426.geometry} material={materials.material_35} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_429.geometry} material={materials.material_35} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_432.geometry} material={materials.material_35} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_435.geometry} material={materials.material_35} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_438.geometry} material={materials.material_35} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_441.geometry} material={materials.material_35} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_444.geometry} material={materials.material_35} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_447.geometry} material={materials.material_35} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_450.geometry} material={materials.material_35} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_453.geometry} material={materials.material_35} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_456.geometry} material={materials.material_35} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_459.geometry} material={materials.material_46} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <group position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh geometry={nodes.Object_463.geometry} material={materials.material_44} />
          <mesh geometry={nodes.Object_465.geometry} material={materials.material_47} />
        </group>
        <mesh geometry={nodes.Object_468.geometry} material={materials.material_47} position={[34.04, 0.03, 10.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <group position={[34.12, -1.7, 12.09]} rotation={[Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Object_622.geometry} material={materials.material_50} />
          <mesh geometry={nodes.Object_626.geometry} material={materials.material_50} />
          <mesh geometry={nodes.Object_625.geometry} material={materials.material_51} />
        </group>
        <group position={[34.12, 1.75, 12.09]} rotation={[Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Object_630.geometry} material={materials.material_50} />
          <mesh geometry={nodes.Object_634.geometry} material={materials.material_50} />
          <mesh geometry={nodes.Object_633.geometry} material={materials.material_51} />
        </group>
        <group position={[34.12, 1.75, 8.65]} rotation={[0, 0, Math.PI]}>
          <mesh geometry={nodes.Object_638.geometry} material={materials.material_50} />
          <mesh geometry={nodes.Object_642.geometry} material={materials.material_50} />
          <mesh geometry={nodes.Object_641.geometry} material={materials.material_51} />
        </group>
        <group position={[34.12, -1.7, 8.65]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
          <mesh geometry={nodes.Object_646.geometry} material={materials.material_50} />
          <mesh geometry={nodes.Object_650.geometry} material={materials.material_50} />
          <mesh geometry={nodes.Object_649.geometry} material={materials.material_51} />
        </group>
        <mesh geometry={nodes.Object_654.geometry} material={materials.material_31} position={[20.56, 1.08, 16.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_657.geometry} material={materials.material_31} position={[20.19, 1.08, 16.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_660.geometry} material={materials.material_31} position={[19.82, 1.08, 16.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_663.geometry} material={materials.material_31} position={[19.45, 1.08, 16.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_666.geometry} material={materials.material_31} position={[19.08, 1.08, 16.02]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/plane.gltf')
